// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGjoeZo--_jiTS_yc8LMPzVwOLxj2uj8k',
    appId: '1:729250547121:web:24dd703cc190d23aa52990',
    messagingSenderId: '729250547121',
    projectId: 'fitnessapp-e4df6',
    authDomain: 'fitnessapp-e4df6.firebaseapp.com',
    storageBucket: 'fitnessapp-e4df6.appspot.com',
    measurementId: 'G-02F8PS6X6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4hiBOruQxP2aUTD5UJoEOcqj4fhKNnLk',
    appId: '1:729250547121:android:2c097c9b6f6e2f14a52990',
    messagingSenderId: '729250547121',
    projectId: 'fitnessapp-e4df6',
    storageBucket: 'fitnessapp-e4df6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_x9QqEG99lUPhzBXowRRNrX4Z6EKvyL0',
    appId: '1:729250547121:ios:ef01533751687145a52990',
    messagingSenderId: '729250547121',
    projectId: 'fitnessapp-e4df6',
    storageBucket: 'fitnessapp-e4df6.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_x9QqEG99lUPhzBXowRRNrX4Z6EKvyL0',
    appId: '1:729250547121:ios:4a683f9b619c38d3a52990',
    messagingSenderId: '729250547121',
    projectId: 'fitnessapp-e4df6',
    storageBucket: 'fitnessapp-e4df6.appspot.com',
    iosBundleId: 'com.example.fitnessApp.RunnerTests',
  );
}
